version: '3'
services:
  db:
    image: postgres
    volumes:
      - db_vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=myapp
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - yarn
    links:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=myapp
  yarn:
    build:
      context: .
      dockerfile: Dockerfile.yarn
    volumes:
      - .:/myapp
volumes:
  db_vol:
